// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

//go:build haiku && !arm64

package runtime

//go:cgo_import_dynamic libc__errnop _errnop "libroot.so"
//go:cgo_import_dynamic libc_clock_gettime clock_gettime "libroot.so"
//go:cgo_import_dynamic libc_close close "libroot.so"
//go:cgo_import_dynamic libc_exit _exit "libroot.so"
//go:cgo_import_dynamic libc_fcntl fcntl "libroot.so"
//go:cgo_import_dynamic libc_find_thread find_thread "libroot.so"
//go:cgo_import_dynamic libc_getpid getpid "libroot.so"
//go:cgo_import_dynamic libc_kill kill "libroot.so"
//go:cgo_import_dynamic libc_madvise madvise "libroot.so"
//go:cgo_import_dynamic libc_malloc malloc "libroot.so"
//go:cgo_import_dynamic libc_mmap mmap "libroot.so"
//go:cgo_import_dynamic libc_mprotect mprotect "libroot.so"
//go:cgo_import_dynamic libc_munmap munmap "libroot.so"
//go:cgo_import_dynamic libc_open open "libroot.so"
//go:cgo_import_dynamic libc_pipe pipe "libroot.so"
//go:cgo_import_dynamic libc_poll poll "libroot.so"
//go:cgo_import_dynamic libc_raise raise "libroot.so"
//go:cgo_import_dynamic libc_read read "libroot.so"
//go:cgo_import_dynamic libc_sched_yield sched_yield "libroot.so"
//go:cgo_import_dynamic libc_sem_init sem_init "libroot.so"
//go:cgo_import_dynamic libc_sem_post sem_post "libroot.so"
//go:cgo_import_dynamic libc_sem_timedwait sem_timedwait "libroot.so"
//go:cgo_import_dynamic libc_sem_wait sem_wait "libroot.so"
//go:cgo_import_dynamic libc_send_signal send_signal "libroot.so"
//go:cgo_import_dynamic libc_setitimer setitimer "libroot.so"
//go:cgo_import_dynamic libc_shutdown shutdown "libnetwork.so"
//go:cgo_import_dynamic libc_sigaction sigaction#LIBROOT_1_ALPHA4 "libroot.so"
//go:cgo_import_dynamic libc_sigaltstack sigaltstack "libroot.so"
//go:cgo_import_dynamic libc_sigprocmask sigprocmask#LIBROOT_1_ALPHA4 "libroot.so"
//go:cgo_import_dynamic libc_sysconf sysconf#LIBROOT_1_ALPHA4 "libroot.so"
//go:cgo_import_dynamic libc_usleep usleep "libroot.so"
//go:cgo_import_dynamic libc_write write "libroot.so"
//go:cgo_import_dynamic libc_getuid getuid "libroot.so"
//go:cgo_import_dynamic libc_geteuid geteuid "libroot.so"
//go:cgo_import_dynamic libc_getgid getgid "libroot.so"
//go:cgo_import_dynamic libc_getegid getegid "libroot.so"
//go:cgo_import_dynamic libc_pthread_attr_destroy pthread_attr_destroy "libroot.so"
//go:cgo_import_dynamic libc_pthread_attr_init pthread_attr_init "libroot.so"
//go:cgo_import_dynamic libc_pthread_attr_setstacksize pthread_attr_setstacksize "libroot.so"
//go:cgo_import_dynamic libc_pthread_attr_setdetachstate pthread_attr_setdetachstate "libroot.so"
//go:cgo_import_dynamic libc_pthread_create pthread_create "libroot.so"
//go:cgo_import_dynamic libc_pthread_self pthread_self "libroot.so"
//go:cgo_import_dynamic libc_tls_allocate tls_allocate "libroot.so"
//go:cgo_import_dynamic libc_chdir chdir "libroot.so"
//go:cgo_import_dynamic libc_chroot chroot "libroot.so"
//go:cgo_import_dynamic libc_dup2 dup2 "libroot.so"
//go:cgo_import_dynamic libc_execve execve "libroot.so"
//go:cgo_import_dynamic libc_fork fork "libroot.so"
//go:cgo_import_dynamic libc_ioctl ioctl "libroot.so"
//go:cgo_import_dynamic libc_setgid setgid "libroot.so"
//go:cgo_import_dynamic libc_setgroups setgroups "libroot.so"
//go:cgo_import_dynamic libc_setpgid setpgid "libroot.so"
//go:cgo_import_dynamic libc_setrlimit setrlimit "libroot.so"
//go:cgo_import_dynamic libc_setsid setsid "libroot.so"
//go:cgo_import_dynamic libc_setuid setuid "libroot.so"
